name: "Think & Get it Java CI"

on:
  push:
    branches: [ main, master, develop, ft/auth-security-validation ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  backend-build-test:
    name: "Java CI Pipeline"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test with Maven
        run: mvn clean test